# https://pagure.io/python-daemon/issue/94
{% set name = "python-daemon" %}
{% set alt_name = name.replace("-", "_") %}
{% set version = "3.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ alt_name }}-{{ version }}.tar.gz
  sha256: f7b04335adc473de877f5117e26d5f1142f4c9f7cd765408f0877757be5afbf4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    # Install won't work with setuptools >69.5.1
    - setuptools <=69.5.1
    - wheel
    - docutils
    - changelog-chug
  run:
    - python
    - lockfile >=0.10
    # docutils doesn't seem necessary here, but pip check won't pass without it.
    - docutils

test:
  source_files:
    - test
  requires:
    - pip
    - pytest
    - testscenarios # [py<312]
    - pbr
    - testtools
  commands:
    # skip pip check because:
    # testscenarios 0.5.0 requires pbr, which is not installed.
    # testscenarios 0.5.0 requires testtools, which is not installed.
    #- pip check
    # we skip tests for py<312 because of missing testscenarios
    # we also skip test_setup because it fails with: E   ModuleNotFoundError: No module named 'setup'
    ### WARNING ###
    # disabling test because on CI testtools seems to be broken and throws error:
    # E   ModuleNotFoundError: No module named 'extras'
    # tests otherwise pass locally
    #- pytest --ignore test/test_setup.py test  # [py<312]
  imports:
    - daemon

about:
  home: https://pagure.io/python-daemon/
  description: |
    This library implements the well-behaved daemon specification of
    PEP 3143, “Standard daemon process library”.
  license: Apache-2.0
  license_family: Other
  license_file:
    - LICENSE.ASF-2
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/
  doc_url: https://pagure.io/python-daemon

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run
