{% set name = "python-daemon" %}
{% set version = "2.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 261c859be5c12ae7d4286dc6951e87e9e1a70a882a8b41fd926efc1ec4214f73

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  # this module is incompatible on Windows because it uses uid and gid
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    # pkg_resources was removed in setuptools 82.0.0 pin below that
    # to keep python-daemon's `import pkg_resources` working.
    - setuptools <82
    - wheel
    - docutils
    - lockfile >=0.10
  run:
    - python
    - lockfile >=0.10
    - setuptools <82
    # docutils doesn't seem necessary here, but pip check won't pass without it.
    - docutils

test:
  # source_files:
    # - test
    # - setup.py
  # requires:
    # - pip
    # - pytest
    # - testscenarios >=0.4 # [py<312]
    # - setuptools >=62.4.0
    # - pbr
    # - testtools
  # commands:
    # skip pip check because:
    # testscenarios 0.5.0 requires pbr, which is not installed.
    # testscenarios 0.5.0 requires testtools, which is not installed.
    #- pip check
    ### WARNING ###
    # disabling test because testtools 2.3.0 requires recursively extras, fixtures, python-mimeparse,
    # six, traceback2, and unittest2
    # tests otherwise pass locally
    # - pytest --ignore test/test_setup.py test  # [py<312]
  imports:
    - daemon
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pagure.io/python-daemon/
  description: |
    This library implements the well-behaved daemon specification of
    PEP 3143, “Standard daemon process library”.
  license: Apache-2.0
  license_family: Other
  license_file:
    - LICENSE.ASF-2
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/
  doc_url: https://pagure.io/python-daemon

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run
    - missing_pip_check
