{% set version = "2.2.4" %}

package:
  name: python-daemon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-daemon/python-daemon-{{ version }}.tar.gz
  sha256: 57c84f50a04d7825515e4dbf3a31c70cc44414394a71608dee6cfde469e81766
  # https://pagure.io/python-daemon/issue/5
  patches:
    - fix_py3.patch  # [not win]

build:
  skip: True  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - lockfile >=0.10
    - docutils
  run:
    - python
    - lockfile >=0.10

test:
  imports:
    - daemon

about:
  home: https://pagure.io/python-daemon/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.ASF-2
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
