travis:
  secure:
    BINSTAR_TOKEN: aCbqfGiV7ZECNlU+SqVq/Cy3fCUyIzItvH4Z/8e0R4tT4s+V74/v2TxN6gPqmD+7dyaV7m88qAqe0SAbDgWj/rvtVsVwZP2SKwlqdbsa6umdmMrFPot1XX1X7fMC48zI3HEGzJjsxdSeDL+DrmKfhR3AonU6tVeO1G5Uxye5Da59n9uzcWP070xRVr3iIj/hrnqXhGJ4hQk59gC2kbWqsUaM+EhGQFeqOIayh4eaTYJ+MWqQqCm84sJvTPqjzyGGDECKtk7ZGax9JzwRInaTw7z920J9CScV7hfs27vNPmomrMwpcYnz+pgC1E6xfeT5El1+FdJyWDRndOjX2aRdE+SeBaqsm7c+4BSRH8MUc1e67J9EP3MZLHRUGn+cKduf/OZgiC7j6xrs0W+VAfEsU/EQzm8PbP1vLNX0wyFYw1zQLYLtizw/gpVVS5YS3i93B9sKB/VJXW3WGLBVHPpcMPLEGdpUnzpc8ujtN3rv3L2RCPLeBqO3Om+MDk9WDbhVVksJdE3Agxz7PwDFL2UZMzktkZZnjgTZO4d4N3A4UpzvYGkNSCMEhEwAj3FM/Gtuu7ruAAJ2nqj+wWvctGWysy1sQkXmXGmNLNDr7s7hzuJDCOysdvEQptQDK5t5idwcwiojo/QaWS2Oup2zPkoVGzj5i/Ox3CWEgEDXTSfFC+4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
